spring.application.name=adm_universidad
spring.jackson.time-zone=America/Santo_Domingo

# Configuración de JPA / Hibernate base
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Límites de archivos subidos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.profiles.active=local