spring.application.name=adm_universidad
spring.datasource.url=jdbc:mysql://10.0.0.108:3306
spring.datasource.username=uniconnect_app
spring.datasource.password=UniConnect2026!Db

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true