spring.config.import=optional:file:./.env[.properties]

# Base de datos local (lee del .env)
spring.datasource.url=jdbc:mysql://uniconnect-db.ddns.net:3306/uniconnect?createDatabaseIfNotExist=true
spring.datasource.username=uniconnect_dev
spring.datasource.password=ISO9102026!

# Para depurar más fácil en local
spring.jpa.show-sql=true

app.jwt.secreto=mi_clave_secreta_super_segura_12345
app.jwt.expiracion-ms=86400000

# Archivos local
app.archivos.directorio=./uploads